name: Branch Deploy

on:
  issue_comment:
    types: [created]

permissions:
  id-token: write
  pull-requests: write
  deployments: write
  contents: write
  checks: read
  statuses: read

jobs:
  branch-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Branch Deploy
        id: branch-deploy
        uses: github/branch-deploy@v9
        with:
          trigger: '.deploy'
          environment: 'production'
          environment_targets: 'production,staging,development'
          # permissions: 'write,maintain,admin'
          # environment_url_in_comment: true

      - name: Deploy (production)
        if: ${{ steps.branch-deploy.outputs.continue == 'true' && steps.branch-deploy.outputs.environment == 'production' }}
        run: |
          echo "Deploying to production..."
          echo "Branch: ${{ steps.branch-deploy.outputs.ref }}"
          echo "Environment: ${{ steps.branch-deploy.outputs.environment }}"
          # Add your production deployment commands here
          sleep 5
          echo "Production deployment completed"

      - name: Deploy (staging)
        if: ${{ steps.branch-deploy.outputs.continue == 'true' && steps.branch-deploy.outputs.environment == 'staging' }}
        run: |
          echo "Deploying to staging..."
          echo "Branch: ${{ steps.branch-deploy.outputs.ref }}"
          echo "Environment: ${{ steps.branch-deploy.outputs.environment }}"
          # Add your staging deployment commands here
          sleep 3
          echo "Staging deployment completed"
          echo "🔍 Please verify the staging deployment and comment '.confirm-staging' to proceed"

      - name: Wait for staging confirmation
        if: ${{ steps.branch-deploy.outputs.continue == 'true' && steps.branch-deploy.outputs.environment == 'staging' }}
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: ${{ github.actor }}
          minimum-approvals: 1
          issue-title: "Manual approval required for staging deployment"
          issue-body: |
            Please verify the staging deployment for PR #${{ github.event.issue.number }}
            
            **Branch**: ${{ steps.branch-deploy.outputs.ref }}
            **Environment**: staging
            **Requested by**: @${{ github.actor }}
            
            Please check the staging environment and approve this issue to continue.
          exclude-workflow-initiator-as-approver: false

      - name: Deploy (development)
        if: ${{ steps.branch-deploy.outputs.continue == 'true' && steps.branch-deploy.outputs.environment == 'development' }}
        run: |
          echo "Deploying to development..."
          echo "Branch: ${{ steps.branch-deploy.outputs.ref }}"
          echo "Environment: ${{ steps.branch-deploy.outputs.environment }}"
          # Add your development deployment commands here
          sleep 2
          echo "Development deployment completed"