name: Branch Deploy

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  deployments: write
  issues: write
  pull-requests: write

jobs:
  branch-deploy:
    if: github.event.issue.pull_request
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Branch Deploy
        id: branch-deploy
        uses: github/branch-deploy@v9
        with:
          trigger: '.deploy'
          environment: 'production'
          production_environment: 'production'
          environment_targets: 'production,staging,development'
          admins: ${{ github.repository_owner }}
          permissions: 'write,maintain,admin'

      - name: Deploy (production)
        if: ${{ steps.branch-deploy.outputs.continue == 'true' && steps.branch-deploy.outputs.environment == 'production' }}
        run: |
          echo "Deploying to production..."
          echo "Branch: ${{ steps.branch-deploy.outputs.ref }}"
          echo "Environment: ${{ steps.branch-deploy.outputs.environment }}"
          # Add your production deployment commands here
          sleep 5
          echo "Production deployment completed"

      - name: Deploy (staging)
        if: ${{ steps.branch-deploy.outputs.continue == 'true' && steps.branch-deploy.outputs.environment == 'staging' }}
        run: |
          echo "Deploying to staging..."
          echo "Branch: ${{ steps.branch-deploy.outputs.ref }}"
          echo "Environment: ${{ steps.branch-deploy.outputs.environment }}"
          # Add your staging deployment commands here
          sleep 3
          echo "Staging deployment completed"

      - name: Deploy (development)
        if: ${{ steps.branch-deploy.outputs.continue == 'true' && steps.branch-deploy.outputs.environment == 'development' }}
        run: |
          echo "Deploying to development..."
          echo "Branch: ${{ steps.branch-deploy.outputs.ref }}"
          echo "Environment: ${{ steps.branch-deploy.outputs.environment }}"
          # Add your development deployment commands here
          sleep 2
          echo "Development deployment completed"